/*
	File auto generated by 'npm run extract-styles'.
	Do not modify this file directly.
	To create a new theme, copy the 'default' theme and edit the newly created theme instead.
 */

@import '_theme-colors'; // Import arbitrary SCSS files
@import '_color-names';

.theme-default {

	// Your extracted definitions will come here:
<%= theme %>

}